cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [

    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        quantity = kwargs.pop('quantity', 1)
        super().__init__(*args, **kwargs)
        self.fields['quantity'].choices = [(i, str(i)) for i in range(1, quantity + 1)]

    quantity = forms.TypedChoiceField(coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST, quantity=product.quantity)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        product = get_object_or_404(Product, id=item['product_id'])
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True}, quantity=product.quantity)
    return render(request, 'cart/detail.html',
                  {'cart': cart})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load thumbnail %}
{% load static %}

{% block title %}Cart{% endblock %}

{% block content %}
    <h1>Cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Delate</th>
                <th>Unit price</th>
                <th>Total price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href='{{ product.get_absolute_url }}'>
                            {% if product.image %}
                                {% thumbnail product.image 200x200 crop='100%' as img %}
                                <img src="{{ img.url }}">
                            {% else %}
                                {% static "img/no_image.png" as img %}
                                <img src="{{ img }}" style="width:200px; height:200px;">
                            {% endif %}
                           </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action='{% url "cart:cart_add" product.id %}' method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                <input type="submit" value="Change">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action='{% url "cart:cart_remove" product.id %}' method="post">
                                <input type="submit" value="Delate">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">{{ item.price }}PLN</td>
                        <td class="num">{{ item.total_price }}PLN</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Summary</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price }}PLN</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href='{% url "shop:product_list" %}' class="button light">
            Contiune shopping
        </a>
        <a href='{% url "orders:order_create" %}' class="button">Pay</a>
    </p>
{% endblock %}