cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [

    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name="process"),
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.conf import settings
from decimal import Decimal
import stripe
from orders.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        for item in order.items.all():
            session_data['line_items'].append(
                {
                    'price_data':
                        {
                            'unit_amount': int(item.price * Decimal('100')),
                            'currency': 'pln',
                            'product_data':
                                {
                                    'name': item.product.name
                                },
                        },
                    'quantity': item.quantity,
                }
            )
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% block title %}Cancel payment{% endblock %}

{% block content %}
    <h1>Your payment has been canceled</h1>

{% endblock %}

payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% block title %}Payment finish successfully{% endblock %}

{% block content %}
    <h1>Your payment has been successful</h1>
    <p>Thank you :)</p>
{% endblock %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Pay for order{% endblock %}

{% block content %}
    <h1>Summary</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Summary</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
                <tr class='row{% cycle "1" "2" %}'>
                    <td>
                        <img src="{% if item.product.image %}
                                     {{ item.product.image.url }}
                                 {% else %}
                                     {% static 'img/no_image.png' %}
                                 {% endif %}"
                             style="height: 200px; width: 200px;">

                    </td>
                    <td>{{ item.product.name }}</td>
                    <td class="num">{{ item.price }}</td>
                    <td class="num">{{ item.quantity }}</td>
                    <td class="num">{{ item.get_cost }}PLN</td>
                </tr>
            {% endfor %}
        <tr class="total">
            <td colspan="4">Summary</td>
            <td colspan="num">{{ order.get_total_cost }}PLN</td>
        </tr>
        </tbody>
    </table>
    <form action='{% url "payment:process" %}' method="post">
        <input type="submit" value="Pay now">
        {% csrf_token %}
    </form>
{% endblock %}